/run/verbose 1
/control/verbose 1
/run/initialize

/vis/open OGL 1280x720-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose 0

# draw & orient volume
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 45. 45.
/vis/viewer/set/style surface

# draw trajectories & hits
/vis/scene/add/trajectories smooth

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/setRGBA opticalphoton 1 0.5 0.6 0.1
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ red

/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

# re-enable auto refresh stuff
/vis/viewer/set/autoRefresh true
/vis/verbose 1

/control/macroPath macros
